export default {
    color_brand_dark: "#425FE0",
    color_brand: "#5271FF",
    color_neutral_dark: "#1B1B1B",
    color_white: "#FFFFFF",
    color_primary0: "#1a1818",
    color_primary1: "#1B3AC8",
    color_secondary0: "#B092F1",
    color_secondary1: "#CAB1FF",
    color_notification_success: "#00B247",
      color_notification_warn: "#FD951F",
      color_notification_error: "#EE4141",
      color_notification_default: "#3A405B",
    color_disabled: "#1B1E23",
    color_danger_dark: "#6F0000",
    color_danger_light: "#FF6A6A",
    color_log_evaluation: "#FDBA1F",
    color_log_training_plan: "#FD6D1F",
    color_default_progress_bar: "#33DDE8",
}